### ISSUE TITLE
No known class method for selector 'sharedInstance'

### ISSUE THREAD

**Issue by ayushbafna24** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push#103]
<img width="1017" alt="screen shot 2018-04-25 at 11 45 48 pm" src="https://user-images.githubusercontent.com/12123191/39264631-fd29f190-48e2-11e8-9ea1-68c8c6eef195.png">

**Comment by AnanthaKrish** [comment]
@ayushbafna24 this is because of the Xcode versions. Do the following to fix this issue ,

1. in AppDelegate.m file import your  `#import "[your-project-name]-Swift.h"

2. In each error lines, start writing the `[[CDVBMSPush sharedInstance] ....]` you will get the right suggestion from the Xcode itself.

**Comment by ayushbafna24** [comment]
![image](https://user-images.githubusercontent.com/12123191/39289082-46983a7a-4948-11e8-82dd-e8db50461295.png)

**Comment by ayushbafna24** [comment]
How to solve these issue ??

**Comment by ayushbafna24** [comment]
Gentle Reminder....Waiting for a good response

**Comment by AnanthaKrish** [comment]
@ayushbafna24 Please follow any of this solutions - https://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr
